export const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "#f0f0f0",
    padding: "20px",
  },
  calculator: {
    background: "white",
    borderRadius: "10px",
    padding: "20px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
    maxWidth: "320px",
    width: "90%",
  },
  display: {
    width: "90%",
    padding: "15px",
    fontSize: "28px",
    textAlign: "right",
    border: "2px solid #e0e0e0",
    borderRadius: "8px",
    background: "#fafafa",
    color: "#333",
    marginBottom: "15px",
    fontFamily: "monospace",
  },
  buttonGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "10px",
    marginBottom: "10px",
  },
  operatorGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "10px",
    marginBottom: "10px",
  },
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "10px",
  },
  button: {
    padding: "15px",
    fontSize: "15px",
    border: "none",
    borderRadius: "8px",
    background: "#5a67d8",
    color: "white",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  operatorButton: {
    padding: "18px",
    fontSize: "18px",
    border: "none",
    borderRadius: "8px",
    background: "#ed8936",
    color: "white",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  clearButton: {
    padding: "18px",
    fontSize: "18px",
    border: "none",
    borderRadius: "8px",
    background: "#e53e3e",
    color: "white",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  equalsButton: {
    padding: "18px",
    fontSize: "18px",
    border: "none",
    borderRadius: "8px",
    background: "#38a169",
    color: "white",
    cursor: "pointer",
    transition: "background 0.2s",
  },
};
