export const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "#f0f0f0",
    padding: "20px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "bold",
    color: "#333",
    marginBottom: "20px",
  },
  userCard: {
    background: "white",
    borderRadius: "10px",
    padding: "10px",
    marginBottom: "15px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
    maxWidth: "500px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
  },
  userName: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#2d3748",
  },
  userEmail: {
    fontSize: "10px",
    color: "#5a67d8",
  },
  phoneText: {
    fontSize: "16px",
    color: "#38a169",
    fontWeight: "500",
  },
  button: {
    padding: "10px 15px",
    fontSize: "12px",
    fontWeight: "400",
    border: "none",
    borderRadius: "8px",
    background: "#ed8936",
    color: "white",
    cursor: "pointer",
    transition: "background 0.2s",
    alignSelf: "flex-start",
  },
};
